spring.application.name=portfolioBackend

spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/db_portfolio
spring.datasource.username=mrdevv
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

server.servlet.context-path=/api/v1