spring.application.name=portfolioBackend

spring.jpa.database=oracle
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.show-sql=true

logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.servlet.context-path=/api/v1

security.jwt.secret-key=${JWT_SECRET_KEY}